#!/usr/bin/env bash
set -euo pipefail

export LC_ALL=C
export LANG=C

usage() {
  cat <<'USAGE'
Usage: scripts/generate-homebrew-formula.sh --version VERSION --dist DIR [--out FILE]

Generates a Homebrew formula (Formula/aglet.rb) that installs the prebuilt
aglet binary from the GitHub release for VERSION.

Options:
  --version VERSION   Release version, without the leading "v" (e.g. 0.1.0)
  --dist DIR          Directory containing the built *.tar.gz packages
  --out FILE          Output path (default: aglet.rb)

The script computes the SHA-256 for each per-platform tarball it finds. The
following platform tarballs are recognised and mapped to Homebrew blocks:

  aglet-<version>-macos-aarch64.tar.gz   -> on_macos / on_arm
  aglet-<version>-macos-x86_64.tar.gz    -> on_macos / on_intel
  aglet-<version>-linux-x86_64.tar.gz    -> on_linux / on_intel
  aglet-<version>-linux-aarch64.tar.gz   -> on_linux / on_arm
USAGE
}

version=""
dist=""
out="aglet.rb"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) version="${2:-}"; shift 2 ;;
    --dist) dist="${2:-}"; shift 2 ;;
    --out) out="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$version" || -z "$dist" ]]; then
  echo "error: --version and --dist are required" >&2
  usage >&2
  exit 2
fi

if [[ ! -d "$dist" ]]; then
  echo "error: dist directory not found: $dist" >&2
  exit 1
fi

sha_of() {
  local file="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" | awk '{print $1}'
  else
    shasum -a 256 "$file" | awk '{print $1}'
  fi
}

# Emits a url/sha256 pair for a given platform tarball if it exists.
# Args: indent label (for missing warning) tarball-suffix
emit_block() {
  local indent="$1" suffix="$2"
  local file="${dist}/aglet-${version}-${suffix}.tar.gz"
  if [[ ! -f "$file" ]]; then
    echo "warning: missing package for ${suffix}: $file" >&2
    return 1
  fi
  local sha
  sha="$(sha_of "$file")"
  printf '%surl "https://github.com/msnodderly/aglet/releases/download/v#{version}/aglet-#{version}-%s.tar.gz"\n' "$indent" "$suffix"
  printf '%ssha256 "%s"\n' "$indent" "$sha"
}

{
  cat <<EOF
# This file is generated by scripts/generate-homebrew-formula.sh.
# Do not edit by hand; changes are overwritten on each release.
class Aglet < Formula
  desc "Terminal personal information manager inspired by Lotus Agenda"
  homepage "https://github.com/msnodderly/aglet"
  version "${version}"
  license "GPL-3.0-or-later"

  on_macos do
    on_arm do
EOF
  emit_block "      " "macos-aarch64" || true
  cat <<'EOF'
    end
    on_intel do
EOF
  emit_block "      " "macos-x86_64" || true
  cat <<'EOF'
    end
  end

  on_linux do
    on_intel do
EOF
  emit_block "      " "linux-x86_64" || true
  cat <<'EOF'
    end
    on_arm do
EOF
  emit_block "      " "linux-aarch64" || true
  cat <<'EOF'
    end
  end

  def install
    bin.install "aglet"
  end

  test do
    assert_match "aglet", shell_output("#{bin}/aglet --help")
  end
end
EOF
} > "$out"

echo "wrote $out"
